

<div id="form-connect">
    <!-- zone de connexion -->
    
    <form action="index.php?action=connect" method="POST">
        <h1><i class="fas fa-user"></i> Espace Client</h1>
        
        <label><b><i class="far fa-envelope"></i>Email:</b></label>
        <input type="text" placeholder="Entrer votre identifiant" name="mail" required>

        <label><b><i class="fas fa-lock"></i>Mot de passe:</b></label>
        <input type="password" placeholder="Entrer le mot de passe" name="password" required>

        <input type="submit" id='submit' value='Se connecter' >
        
    </form>
    <a href="index.php?action=create">Creer un compte</a>
</div>