<?php if($admin->is_admin() == false): ?>
<?php header ('Location: index.php'); ?>
<?php endif; ?>

  <fieldset>
    <legend><i class="fas fa-list"></i> Liste des Commandes</legend>
 <table class="list-product">
   <thead>
        <tr>
            <th>id</th>
            <th>Date</th>
            <th>Nom</th>
            <th>Prix Total</th>
            <th>Détails</th>
            <th>Supprimer</th>
        </tr>
    </thead>    

<?php foreach($commandes as $commande): ?>
<tr>
  <td><?= $commande['id'] ?></td>
  <td><?= $commande['DATE'] ?> à <?= $commande['HEURE'] ?></td>
	<td><?= $commande['nom'] ?> <?= $commande['prenom'] ?></td>
	<td><?= $commande['prix_total'] ?></td>
	<td><a href="index.php?action=affichage_details_commande&id=<?= $commande['id'] ?>"><i class="fas fa-eye"></i></a></td>
	<td><a href="index.php?action=supprimer_commande&id=<?= $commande['id'] ?>"><i class="far fa-trash-alt"></i></a></td>
</tr>    
    <?php endforeach; ?>
</table>   
  </fieldset>  
