

<div class="section-title">
        <h2 class="animated fadeIn delay-1s">Carte du restaurant</h2>
</div>


	<section id="articles" class="display1 container">
	    <?php foreach($meals as $plat): ?>
    <article class="">
    <a href="#"><img width="400px" height="300px" src='www/images/<?= $plat['photo'] ?>'></a>
   		<h3><?= $plat['name'] ?></h3>
			<p><?= $plat['description'] ?></p>
			<span class='price'><?= $plat['prix2']."€" ?></span>
    </article>
    <?php endforeach; ?>

	</section>